name: logzy
env: local
slack-uri: { SLACK_WEBHOOK_URI }
target-service: account-service-LOCAL
log-file-name: account-service-DEV-error.log
log-location: ./logzy
logger-file-location: ./log/logzy
response-timeout: 30
start-error-patterns:
  [
    '(\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}\+\d{4}) \| (ERROR) \| ([A-Z_]+) \| (\w+) \| (\w+) \| (.+)',
    "(?i)shutting down|shutdown completed|shutdown requested",
    'OutOfMemoryError|Critical\sError',
  ]